{% set major = "1.46" %}
{% set patch = "0" %}
{% set version = major + "." + patch %}

package:
  name: pango
  version: {{ version }}

source:
  url: http://ftp.gnome.org/pub/GNOME/sources/pango/{{ major }}/pango-{{ version }}.tar.xz
  sha256: 9a81572ebb946187fbdd69d5ffc57e2f7a1f768cd8d2fd89dbb03fb9002a99b5
  patches:
    # pc file patch should not be needed for version 1.43+
    - windows_fix_libm_in_pc_file.patch  # [win]

build:
  number: 0
  skip: true  # [win and vc<14]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - meson
    - ninja
    - pkg-config
    - pthread-stubs  # [linux]
    - {{ compiler('c') }}
  host:
    - gobject-introspection
    - cairo
    - fribidi
    - glib
    - harfbuzz
    - fontconfig
    - freetype
    - libpng
  run:
    - cairo
    - fribidi
    - glib
    - harfbuzz
    - fontconfig
    - freetype
    - libpng

test:
  requires:
    - pkg-config
  commands:
    - pango-view --help
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

    # check that libraries are installed and can be found through pkg-config
    # (used by downstream builds)
    {% set libs = [
        "pango",
        "pangocairo",
    ] %}
    {% set libs = libs + ["pangoft2"] %}  # [unix]
    {% set libs = libs + ["pangowin32"] %}  # [win]
    {% for lib in libs %}
    - test -f $PREFIX/lib/lib{{ lib }}-1.0${SHLIB_EXT}  # [unix]
    - test -f `pkg-config --variable=libdir --dont-define-prefix {{ lib }}`/lib{{ lib }}-1.0${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\bin\\{{ lib }}-1.0-0.dll exit 1  # [win]
    - for /f "usebackq tokens=*" %%a in (`pkg-config --variable=exec_prefix --dont-define-prefix {{ lib }}`) do if not exist "%%a/bin/{{ lib }}-1.0-0.dll" exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\{{ lib }}-1.0.lib exit 1  # [win]
    - for /f "usebackq tokens=*" %%a in (`pkg-config --variable=libdir --dont-define-prefix {{ lib }}`) do if not exist "%%a/{{ lib }}-1.0.lib" exit 1  # [win]
    {% endfor %}

about:
  home: http://www.pango.org/
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: 'Text layout and rendering engine.'
  description: |
    Pango is a library for laying out and rendering of text, with an emphasis
    on internationalization. Pango can be used anywhere that text layout is
    needed, though most of the work on Pango so far has been done in the
    context of the GTK+ widget toolkit. Pango forms the core of text and font
    handling for GTK+-2.x.
  doc_url: http://www.pango.org/
  dev_url: https://gitlab.gnome.org/GNOME/pango

extra:
  recipe-maintainers:
    - ocefpaf
    - ccordoba12
    - jakirkham
    - pkgw
